//Splash types
const SET_SPLASH_STATUS = 'SET_SPLASH_STATUS';

//Users types
const SET_USERS = 'SET_USERS';
const SET_USERS_LOADER_STATUS = 'SET_USERS_LOADER_STATUS';
const SET_USERS_ERROR = 'SET_USERS_ERROR';

export {
    SET_SPLASH_STATUS,

    SET_USERS,
    SET_USERS_LOADER_STATUS,
    SET_USERS_ERROR,
}
